-- 1. Basic SELECT with WHERE: Find all cars currently available for rent
SELECT Make, Model, Year, Status 
FROM Cars 
WHERE Status = 'Available';

-- 2. INNER JOIN: Display car details alongside their specific category names and rates
SELECT c.Make, c.Model, cat.CategoryName, cat.DailyRate
FROM Cars c
INNER JOIN CarCategories cat ON c.CategoryID = cat.CategoryID;

-- 3. LEFT JOIN: List all customers and any rentals they have made (including those with zero rentals)
SELECT cu.FirstName, cu.LastName, r.RentalDate, r.TotalAmount
FROM Customers cu
LEFT JOIN Rentals r ON cu.CustomerID = r.CustomerID;

-- 4. GROUP BY: Count how many cars are stationed at each branch location
SELECT l.BranchName, COUNT(c.CarID) AS TotalCarsAtLocation
FROM Locations l
JOIN Cars c ON l.LocationID = c.LocationID
GROUP BY l.BranchName;

-- 5. WHERE: Identify customers who have rented from the 'Luxury' category
SELECT FirstName, LastName, Email
FROM Customers
WHERE CustomerID IN (
    SELECT r.CustomerID
    FROM Rentals r
    JOIN Cars c ON r.CarID = c.CarID
    JOIN CarCategories cat ON c.CategoryID = cat.CategoryID
    WHERE cat.CategoryName = 'Luxury'
);

-- 6. HAVING: Find locations that have processed more than 2 rental transactions
SELECT PickupLocationID, COUNT(*) AS RentalCount
FROM Rentals
GROUP BY PickupLocationID
HAVING COUNT(*) > 2;

-- 7. Multiple JOINs: Create a complete rental report showing customer, car, and payment details
SELECT r.RentalID, cu.LastName, c.Make, c.Model, p.Amount, p.PaymentMethod
FROM Rentals r
JOIN Customers cu ON r.CustomerID = cu.CustomerID
JOIN Cars c ON r.CarID = c.CarID
JOIN Payments p ON r.RentalID = p.RentalID;

-- 8. Subquery in SELECT: Show each payment amount alongside the total revenue of the company
SELECT PaymentID, Amount, 
       (SELECT SUM(Amount) FROM Payments) AS CompanyTotalRevenue
FROM Payments;

-- 9. Date Function Query: Calculate the duration of each rental in days using DATEDIFF
SELECT RentalID, RentalDate, ReturnDate, 
       DATEDIFF(day, RentalDate, ReturnDate) AS DurationDays
FROM Rentals
WHERE ReturnDate IS NOT NULL;

-- 10. Complex Query: Total revenue generated by each car category, sorted from highest to lowest
SELECT cat.CategoryName, SUM(p.Amount) AS CategoryRevenue
FROM CarCategories cat
JOIN Cars c ON cat.CategoryID = c.CategoryID
JOIN Rentals r ON c.CarID = r.CarID
JOIN Payments p ON r.RentalID = p.RentalID
GROUP BY cat.CategoryName
ORDER BY CategoryRevenue DESC;